### ISSUE TITLE
Button not showing with the right format

### ISSUE THREAD

**Issue by G-Pereira** [msramalho/SigToCa#4]
In both Schedule and Exams page this button displays with the following format:

![screenshot from 2018-02-01 10-08-55](https://user-images.githubusercontent.com/15521303/35672884-cd3118b6-0737-11e8-9bef-579beea48ee4.png)

Here it is a bunch of information that might be relevant:

- Version 1.1 of this app
- OS: Arch Linux x86_64
- Kernel: 4.14.15-1-ARCH
- Chrome: 64.0.3282.119 (Developer Build) (64-bit)

And here it is a zip with the downloaded webpage:
[FEUP - Mapa de Exames.zip](https://github.com/msramalho/SigToCa/files/1684988/FEUP.-.Mapa.de.Exames.zip)

**Comment by msramalho** [comment]
This is a problem with your Chrome environment which does not support _emoji_, one option would be to use an image instead of an emoji for the button, but I don't think it is a priority or really that necessary due to the fact that most browsers do have that feature. 

For this, I am closing this issue. But if someone does change the emoji for an icon with no design differences, I'll accept the PR.
